apiVersion: v1
name: bookstack
description: BookStack is a simple, self-hosted, easy-to-use platform for organising and storing information.
type: application
version: 1.5.0
appVersion: 22.04.02
home: https://www.bookstackapp.com/
icon: https://media.githubusercontent.com/media/BookStackApp/website/master/static/images/logo.png
sources:
- https://github.com/BookStackApp/BookStack
maintainers:
- name: verwilst
  email: bart@verwilst.be
- name: baskoopmans
  email: helm@baskoopmans.nl
